"""
training_debugging_vocabulary.py
================================
Controlled vocabulary mapping natural-language phrases to Fact class names.

This is *data*, not logic: each entry is a controlled trigger phrase mapped
to the symptom or model-type Fact name(s) it should emit. The matcher in
entity_mapper.py lemmatises phrases with spaCy before lookup; no diagnostic
inference lives here.
"""

from __future__ import annotations

FactNameSpec = str | tuple[str, ...]


# phrase -> Fact class name(s). Phrases are matched by spaCy lemmas against
# the controlled vocabulary. Order does not matter; all matches are collected.
SYMPTOM_PHRASES: dict[str, FactNameSpec] = {
    # loss behaviour
    "oscillate": "OscillatingLoss",
    "loss oscillates": "OscillatingLoss",
    "loss is oscillating": "OscillatingLoss",
    "loss keeps oscillating": "OscillatingLoss",
    "loss bounces": "OscillatingLoss",
    "loss fluctuates": "OscillatingLoss",
    "loss spikes": "OscillatingLoss",
    "training loss high": "TrainingLossHigh",
    "training loss is high": "TrainingLossHigh",
    "training loss still high": "TrainingLossHigh",
    "training loss is still high": "TrainingLossHigh",
    "high training loss": "TrainingLossHigh",
    "loss stays high": "TrainingLossHigh",
    "loss not decreasing": "TrainingLossHigh",
    "loss never converges": "TrainingLossHigh",
    "never converges": "TrainingLossHigh",
    "loss plateau": ("TrainingLossHigh", "SlowConvergence"),
    "loss stuck": "TrainingLossHigh",
    "stuck loss": "TrainingLossHigh",
    "validation loss high": "ValidationLossHigh",
    "validation loss is high": "ValidationLossHigh",
    "high validation loss": "ValidationLossHigh",
    "val loss high": "ValidationLossHigh",
    # nan / explosion
    "nan": "NaNLoss",
    "nans": "NaNLoss",
    "not a number": "NaNLoss",
    "loss becomes inf": "NaNLoss",
    "infinite loss": "NaNLoss",
    "loss goes to infinity": "NaNLoss",
    "goes to infinity": "NaNLoss",
    "inf loss": "NaNLoss",
    "overflow": "NaNLoss",
    "explode": "GradientExplosion",
    "loss explodes": "GradientExplosion",
    "loss is exploding": "GradientExplosion",
    "loss blows up": "GradientExplosion",
    "blows up": "GradientExplosion",
    "gradient explosion": "GradientExplosion",
    "gradient explodes": "GradientExplosion",
    "exploding gradient": "GradientExplosion",
    "gradients blow up": "GradientExplosion",
    "gradient vanishes": "GradientVanishing",
    "gradients are vanishing": "GradientVanishing",
    "vanishing gradient": "GradientVanishing",
    "gradients are zero": "GradientVanishing",
    "gradients near zero": "GradientVanishing",
    "gradients look near zero": "GradientVanishing",
    "early layers not learning": "GradientVanishing",
    "early layers barely learning": "GradientVanishing",
    "early layers are barely learning": "GradientVanishing",
    "gradient underflow": "GradientUnderflow",
    "gradients underflow": "GradientUnderflow",
    "underflowing gradients": "GradientUnderflow",
    # convergence
    "slow convergence": "SlowConvergence",
    "converges slowly": "SlowConvergence",
    "converging slowly": "SlowConvergence",
    "converges very slowly": "SlowConvergence",
    "converging very slowly": "SlowConvergence",
    "training is slow": "SlowConvergence",
    "barely improves": "SlowConvergence",
    "will not learn": "SlowConvergence",
    "wont learn": "SlowConvergence",
    "stuck": "SlowConvergence",
    "plateau": "SlowConvergence",
    "training plateau": "SlowConvergence",
    # accuracy
    "training accuracy high": "TrainingAccuracyHigh",
    "training accuracy is high": "TrainingAccuracyHigh",
    "high training accuracy": "TrainingAccuracyHigh",
    "99% training": "TrainingAccuracyHigh",
    "training accuracy low": "TrainingAccuracyLow",
    "training accuracy is low": "TrainingAccuracyLow",
    "low training accuracy": "TrainingAccuracyLow",
    "training accuracy and validation accuracy are low": (
        "TrainingAccuracyLow",
        "ValidationAccuracyLow",
    ),
    "both training and validation accuracy are low": (
        "TrainingAccuracyLow",
        "ValidationAccuracyLow",
    ),
    "both training accuracy and validation accuracy are low": (
        "TrainingAccuracyLow",
        "ValidationAccuracyLow",
    ),
    "validation accuracy low": "ValidationAccuracyLow",
    "validation accuracy is low": "ValidationAccuracyLow",
    "low validation accuracy": "ValidationAccuracyLow",
    "validation accuracy much lower": "ValidationAccuracyLow",
    "validation accuracy is much lower": "ValidationAccuracyLow",
    "val accuracy lower": "ValidationAccuracyLow",
    "train validation gap": "ValidationAccuracyLow",
    "train val gap": "ValidationAccuracyLow",
    "accuracy gap": "ValidationAccuracyLow",
    "validation accuracy high": "ValidationAccuracyHigh",
    "validation accuracy is high": "ValidationAccuracyHigh",
    "high validation accuracy": "ValidationAccuracyHigh",
    "test accuracy low": "TestAccuracyLow",
    "test accuracy is low": "TestAccuracyLow",
    "low test accuracy": "TestAccuracyLow",
    "poor on test": "TestAccuracyLow",
    # generalisation / overfit phrasing
    "memorize": "OverfittingObserved",
    "memorising": "OverfittingObserved",
    "overfit": "OverfittingObserved",
    "underfit": "UnderfittingObserved",
    "generalise": "PoorGeneralization",
    "generalize": "PoorGeneralization",
    # data
    "class imbalance": "ClassImbalanceDetected",
    "imbalanced dataset": "ClassImbalanceDetected",
    "data leak": "DataLeakageSuspected",
    "data leakage": "DataLeakageSuspected",
    "split leakage": "DataLeakageSuspected",
    "train test contamination": "DataLeakageSuspected",
    "leaking data": "DataLeakageSuspected",
    "leakage": "DataLeakageSuspected",
    "noisy label": "NoisyLabels",
    "noisy labels": "NoisyLabels",
    "labels are noisy": "NoisyLabels",
    "label noise": "NoisyLabels",
    "mislabel": "NoisyLabels",
    "small dataset": "SmallDataset",
    "dataset is small": "SmallDataset",
    "few examples": "SmallDataset",
    "not much data": "SmallDataset",
    "little data": "SmallDataset",
    "tiny dataset": "SmallDataset",
    "large dataset": "LargeDataset",
    "millions of examples": "LargeDataset",
    # architecture-specific symptoms
    "dead relu": "DeadReLUDetected",
    "dying relu": "DeadReLUDetected",
    "units output zero": "DeadReLUDetected",
    "attention collapse": "AttentionCollapse",
    "attention is uniform": "AttentionCollapse",
    "attends to one token": "AttentionCollapse",
    "attention entropy collapse": "AttentionEntropyCollapse",
    "attention entropy collapses": "AttentionEntropyCollapse",
    "repetitive text": "RepetitiveGeneration",
    "outputs repetitive text": "RepetitiveGeneration",
    "repetitive generation": "RepetitiveGeneration",
    "tokenize": "TokenizationIssue",
    "tokenization": "TokenizationIssue",
    "lots of unk": "TokenizationIssue",
    "out of vocabulary": "TokenizationIssue",
    "context length": "ContextLengthExceeded",
    "sequence too long": "ContextLengthExceeded",
    "max length exceeded": "ContextLengthExceeded",
    "feature collapse": "FeatureCollapse",
    "feature maps constant": "FeatureCollapse",
    "feature maps are constant": "FeatureCollapse",
    "receptive field": "ReceptiveFieldTooSmall",
    "runs out of memory on long sequences": "LongSequenceMemoryBlowup",
    "out of memory on long sequences": "LongSequenceMemoryBlowup",
    "long sequence memory": "LongSequenceMemoryBlowup",
    "positional encoding problem": "PositionalEncodingProblem",
    "positional encoding problems": "PositionalEncodingProblem",
    "warmup missing": "WarmupMissing",
    "warmup is missing": "WarmupMissing",
    "batch norm train eval mismatch": "BatchNormTrainEvalMismatch",
    "batch norm behaves differently between train and eval": "BatchNormTrainEvalMismatch",
    "aggressive pooling": "AggressivePoolingOrStride",
    "aggressive stride": "AggressivePoolingOrStride",
    "loses spatial details": "AggressivePoolingOrStride",
    "low throughput": "MultiGpuThroughputLow",
    "throughput is low": "MultiGpuThroughputLow",
    "training throughput is low": "MultiGpuThroughputLow",
    "gpu underutilization": "GpuUnderutilization",
    "gpus are underutilized": "GpuUnderutilization",
    "gpu underutilized": "GpuUnderutilization",
    "gpu idle": "GpuUnderutilization",
    "gpus are idle": "GpuUnderutilization",
    "gpus idle": "GpuUnderutilization",
    "slow gradient synchronization": "GradientSyncSlow",
    "gradient synchronization is slow": "GradientSyncSlow",
    "batch norm desync": "BatchNormDesync",
    "batch norm stats are desynchronized": "BatchNormDesync",
    "batch norm stats desynchronized": "BatchNormDesync",
    "coupled weight decay": "CoupledWeightDecayUsed",
    "coupled l2 weight decay": "CoupledWeightDecayUsed",
    "adam with coupled weight decay": "CoupledWeightDecayUsed",
}

CAUSE_PHRASES: dict[str, FactNameSpec] = {
    "learning rate too high": "LearningRateTooHigh",
    "learning rate is too high": "LearningRateTooHigh",
    "high learning rate": "LearningRateTooHigh",
    "learning rate too low": "LearningRateTooLow",
    "learning rate is too low": "LearningRateTooLow",
    "low learning rate": "LearningRateTooLow",
    "distribution shift": "DistributionShift",
    "different distribution": "DistributionShift",
    "different distribution than training": "DistributionShift",
    "test data from a different distribution": "DistributionShift",
}

# Model-type detection phrases.
MODEL_TYPE_PHRASES: dict[str, FactNameSpec] = {
    "transformer": "ModelIsTransformer",
    "attention": "ModelIsTransformer",
    "bert": "ModelIsTransformer",
    "gpt": "ModelIsTransformer",
    "llm": "ModelIsTransformer",
    "self-attention": "ModelIsTransformer",
    "vision transformer": "ModelIsTransformer",
    "vit": "ModelIsTransformer",
    "cnn": "ModelIsCNN",
    "convolution": "ModelIsCNN",
    "conv net": "ModelIsCNN",
    "convnet": "ModelIsCNN",
    "resnet": "ModelIsCNN",
    "vgg": "ModelIsCNN",
}

CONTEXT_PHRASES: dict[str, FactNameSpec] = {
    "mixed precision": "UsesMixedPrecision",
    "automatic mixed precision": "UsesMixedPrecision",
    "amp": "UsesMixedPrecision",
    "fp16": "UsesMixedPrecision",
    "bf16": "UsesMixedPrecision",
    "distributed training": "UsesDistributedTraining",
    "multi gpu": "UsesDistributedTraining",
    "multi device": "UsesDistributedTraining",
    "across gpus": "UsesDistributedTraining",
    "ddp": "UsesDistributedTraining",
    "adam": "OptimizerIsAdam",
    "adamw": "OptimizerIsAdam",
    "sgd": "OptimizerIsSGD",
}

# Synonym normalisation applied before phrase matching.
SYNONYMS: dict[str, str] = {
    "acc": "accuracy",
    "lr": "learning rate",
    "val": "validation",
    "grads": "gradients",
    "grad": "gradient",
    "diverge": "explode",
    "diverging": "exploding",
    "blowing up": "exploding",
    "wont": "will not",
}
